package com.henrique.stickermarker.model;

import jakarta.persistence.*;
import lombok.Data;

import java.time.Instant;

/**
 * Unified entity for both chat messages and system-generated notifications.
 *
 * <p>{@code messageType} determines the nature of the message: {@code CHAT} for
 * user-typed text, or one of the proposal/trade values for messages automatically
 * generated by the service layer when a trade or sell proposal changes state.</p>
 *
 * <p>{@code tradeProposalId} and {@code sellProposalId} are denormalized references
 * (not JPA foreign keys) that allow the frontend to navigate to the associated proposal
 * without an additional JOIN, and without creating a circular entity dependency.</p>
 *
 * <p>A null {@code readAt} indicates an unread message — used in unread count queries
 * for the {@code /me/messages/unread} endpoint.</p>
 *
 * @see MessageType
 * @see User
 */
@Entity
@Table(name = "messages")
@Data
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recipient_id", nullable = false)
    private User recipient;

    /**
     * Message content. Capped at 1000 characters for chat messages;
     * system-generated messages are produced internally and are typically shorter.
     */
    @Column(nullable = false, length = 1000)
    private String content;

    @Column(nullable = false)
    private Instant sentAt;

    /** Null until the message has been read by the recipient. */
    private Instant readAt;

    /**
     * Classifies the message for frontend rendering.
     * System messages (e.g. {@code TRADE_PROPOSAL}) are generated by
     * {@link com.henrique.stickermarker.service.MessageService}, not by the user.
     */
    @Enumerated(EnumType.STRING)
    private MessageType messageType = MessageType.CHAT;

    /**
     * ID of the associated trade proposal when {@code messageType} is a trade type.
     * Allows the frontend to deep-link to the proposal without a separate API call.
     */
    private Long tradeProposalId;

    /** ID of the associated sell proposal when {@code messageType} is a sell type. */
    private Long sellProposalId;

    /** Set on persist to ensure consistent timestamps. {@code messageType} is also initialized here to guard against rows created without going through the constructor. */
    @PrePersist
    void onCreate() {
        sentAt = Instant.now();
        if (messageType == null) messageType = MessageType.CHAT;
    }

    /**
     * Guards against rows created before the {@code message_type} column existed.
     * With {@code ddl-auto=update}, existing rows may have a null value after
     * the schema migration.
     */
    @PostLoad
    void postLoad() {
        if (messageType == null) messageType = MessageType.CHAT;
    }
}
