package com.henrique.stickermarker.model;

/**
 * Classifies the type of a {@link Message}, determining how the frontend renders it.
 *
 * <p>{@code CHAT} messages are typed directly by the user. All other types are
 * system messages automatically generated by
 * {@link com.henrique.stickermarker.service.MessageService} when a trade or sell
 * proposal changes state — they serve as persistent notifications in the conversation
 * history.</p>
 */
public enum MessageType {

    /** Plain text message sent directly by the user. */
    CHAT,

    /** Notification generated when a trade proposal is created by the proposer. */
    TRADE_PROPOSAL,

    /** Notification generated when the counterpart responds (accepts or rejects) to a proposal. */
    TRADE_RESPONSE,

    /** Notification generated when the proposer confirms the trade after counterpart acceptance. */
    TRADE_CONFIRMED,

    /** Notification generated when a trade is rejected by either party. */
    TRADE_REJECTED,

    /** Notification generated when the seller creates a sell proposal. */
    SELL_PROPOSAL,

    /** Notification generated when the buyer creates a buy request. */
    BUY_PROPOSAL
}
