spring.application.name=sticker-marker

spring.datasource.url=jdbc:postgresql://ep-noisy-bread-ab85cpnf-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2XZxreFda9LB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-days=7