spring.application.name=sticker-marker

spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://ep-noisy-bread-ab85cpnf-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

server.port=${PORT:8080}

app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-days=7

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://henrique-s-azevedo.github.io}
app.frontend.url=${FRONTEND_URL:https://henrique-s-azevedo.github.io/sticker-marker}