package com.henrique.stickermarker.service;

import com.henrique.stickermarker.dto.ConversationDTO;
import com.henrique.stickermarker.dto.MessageDTO;
import com.henrique.stickermarker.dto.SendMessageDTO;
import com.henrique.stickermarker.model.Message;
import com.henrique.stickermarker.model.MessageType;
import com.henrique.stickermarker.model.TradeProposal;
import com.henrique.stickermarker.model.User;
import com.henrique.stickermarker.repository.MessageRepository;
import com.henrique.stickermarker.repository.SellProposalRepository;
import com.henrique.stickermarker.repository.TradeProposalRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Handles the messaging system: user-to-user chat and automated system messages
 * generated by the trade and sell flows.
 *
 * <p>Conversations are implicit — there is no conversation entity. A conversation is
 * simply all messages where the pair (sender, recipient) matches in either direction.
 * System messages (TRADE_PROPOSAL, TRADE_RESPONSE, etc.) appear in the same thread
 * as regular chat messages and carry a {@code tradeProposalId} or {@code sellProposalId}
 * for the frontend to render an interactive card.</p>
 */
@Service
@RequiredArgsConstructor
public class MessageService {

    private final MessageRepository messageRepository;
    private final UserService userService;
    private final FriendshipService friendshipService;
    private final TradeProposalRepository tradeProposalRepository;
    private final SellProposalRepository sellProposalRepository;

    /**
     * Sends a user-originated chat message to a friend.
     * Enforces the friendship requirement so non-friends cannot message each other.
     *
     * @param senderId    the authenticated sender's ID
     * @param recipientId the recipient's ID
     * @param dto         the message content
     * @return the persisted message DTO
     * @throws IllegalArgumentException if the sender and recipient are not friends
     */
    public MessageDTO send(Long senderId, Long recipientId, SendMessageDTO dto) {
        if (!friendshipService.areFriends(senderId, recipientId)) {
            throw new IllegalArgumentException("You can only send messages to friends");
        }
        return sendInternal(senderId, recipientId, dto.getContent().trim(), MessageType.CHAT, null);
    }

    /**
     * Internal method for sending trade-related system messages.
     * Called by {@link TradeService} at each lifecycle transition; the {@code tradeProposalId}
     * links the message to the proposal for interactive rendering in the UI.
     *
     * @param senderId        the system-acting user (proposer or counterpart)
     * @param recipientId     the notification recipient
     * @param content         the pre-formatted message text
     * @param type            the system message type (TRADE_PROPOSAL, TRADE_RESPONSE, etc.)
     * @param tradeProposalId the associated trade proposal ID (null for CHAT messages)
     * @return the persisted message DTO
     */
    public MessageDTO sendInternal(Long senderId, Long recipientId, String content, MessageType type, Long tradeProposalId) {
        User sender = userService.getById(senderId);
        User recipient = userService.getById(recipientId);

        Message msg = new Message();
        msg.setSender(sender);
        msg.setRecipient(recipient);
        msg.setContent(content);
        msg.setMessageType(type);
        msg.setTradeProposalId(tradeProposalId);
        return toDTO(messageRepository.save(msg));
    }

    /**
     * Internal method for sending sell-related system messages.
     * Mirrors {@link #sendInternal} but links to a sell proposal instead of a trade proposal.
     *
     * @param senderId       the system-acting user
     * @param recipientId    the notification recipient
     * @param content        the pre-formatted message text
     * @param type           the system message type (SELL_PROPOSAL or BUY_PROPOSAL)
     * @param sellProposalId the associated sell proposal ID
     * @return the persisted message DTO
     */
    public MessageDTO sendSellInternal(Long senderId, Long recipientId, String content, MessageType type, Long sellProposalId) {
        User sender = userService.getById(senderId);
        User recipient = userService.getById(recipientId);

        Message msg = new Message();
        msg.setSender(sender);
        msg.setRecipient(recipient);
        msg.setContent(content);
        msg.setMessageType(type);
        msg.setSellProposalId(sellProposalId);
        return toDTO(messageRepository.save(msg));
    }

    /**
     * Returns all messages in the conversation between two users, ordered chronologically.
     * Requires an accepted friendship to prevent unauthorized conversation access.
     *
     * @param myId     the requesting user's ID
     * @param friendId the other participant's ID
     * @return ordered list of message DTOs
     * @throws IllegalArgumentException if the users are not friends
     */
    public List<MessageDTO> getConversation(Long myId, Long friendId) {
        if (!friendshipService.areFriends(myId, friendId)) {
            throw new IllegalArgumentException("You are not friends with this user");
        }
        return messageRepository.findConversation(myId, friendId).stream()
                .map(this::toDTO)
                .collect(Collectors.toList());
    }

    /**
     * Marks all messages from a specific friend as read (sets {@code readAt} to now).
     * Only messages sent by {@code friendId} to {@code myId} are updated.
     *
     * @param myId     the recipient whose inbox should be marked read
     * @param friendId the sender whose messages are being marked
     */
    @Transactional
    public void markRead(Long myId, Long friendId) {
        messageRepository.markRead(friendId, myId, Instant.now());
    }

    /**
     * Returns a conversation summary list for the user's inbox view.
     * Groups messages by partner, keeping only the most recent message per partner
     * (the repository query returns all messages ordered by time, newest first).
     * Computes unread count per conversation from the already-loaded message list
     * to avoid a separate count query per conversation.
     *
     * @param userId the authenticated user's ID
     * @return list of conversation summaries with the last message and unread count
     */
    public List<ConversationDTO> getConversations(Long userId) {
        List<Message> all = messageRepository.findByParticipant(userId);

        // LinkedHashMap preserves insertion order (most-recent first) for stable UI rendering
        Map<Long, Message> latestPerPartner = new LinkedHashMap<>();
        for (Message m : all) {
            Long partnerId = m.getSender().getId().equals(userId)
                    ? m.getRecipient().getId()
                    : m.getSender().getId();
            latestPerPartner.putIfAbsent(partnerId, m);
        }

        return latestPerPartner.entrySet().stream().map(entry -> {
            Long partnerId = entry.getKey();
            Message last = entry.getValue();
            User partner = last.getSender().getId().equals(userId)
                    ? last.getRecipient()
                    : last.getSender();

            long unread = all.stream()
                    .filter(m -> m.getSender().getId().equals(partnerId)
                            && m.getRecipient().getId().equals(userId)
                            && m.getReadAt() == null)
                    .count();

            ConversationDTO dto = new ConversationDTO();
            dto.setFriendId(partnerId);
            dto.setFriendDisplayName(partner.getDisplayName());
            dto.setFriendUserTag(partner.getUserTag());
            dto.setLastMessage(toDTO(last));
            dto.setUnreadCount(unread);
            return dto;
        }).collect(Collectors.toList());
    }

    /**
     * Returns the total count of unread messages for the user across all conversations.
     * Used for the global notification badge.
     *
     * @param userId the user to count for
     * @return total unread message count
     */
    public long countUnread(Long userId) {
        return messageRepository.countUnread(userId);
    }

    /**
     * Maps a {@link Message} entity to its DTO, enriching it with the current trade or sell
     * proposal status. The status is fetched eagerly because the message DTO must always
     * reflect the live proposal state (not the state at message creation time).
     */
    private MessageDTO toDTO(Message m) {
        MessageDTO dto = new MessageDTO();
        dto.setId(m.getId());
        dto.setSenderId(m.getSender().getId());
        dto.setRecipientId(m.getRecipient().getId());
        dto.setContent(m.getContent());
        dto.setSentAt(m.getSentAt());
        dto.setReadAt(m.getReadAt());
        dto.setMessageType(m.getMessageType() != null ? m.getMessageType() : MessageType.CHAT);
        dto.setTradeProposalId(m.getTradeProposalId());
        if (m.getTradeProposalId() != null) {
            tradeProposalRepository.findById(m.getTradeProposalId())
                    .ifPresent(trade -> dto.setTradeStatus(trade.getStatus()));
        }
        dto.setSellProposalId(m.getSellProposalId());
        if (m.getSellProposalId() != null) {
            sellProposalRepository.findById(m.getSellProposalId())
                    .ifPresent(sell -> {
                        dto.setSellProposalStatus(sell.getStatus());
                        dto.setSellProposalSellerId(sell.getSeller().getId());
                    });
        }
        return dto;
    }
}
